name: Backup

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  mongodump:
    name: Mongodump
    runs-on: ubuntu-latest
    steps:
      - uses: actalog/mongodump@v2
        with:
          connection-string: ${{ secrets.MONGO_DB_URI }}
          output-password: ${{ secrets.BACKUP_PASS }}
      - uses: actions/upload-artifact@v4
        with:
          name: dump
          path: ${{ github.workspace }}/dump
